name: 'ratings'
version: '1.0.0'
config-version: 2

profile: 'ratings'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ratings:
    "01_staging":
      +materialized: view
      +schema: staging
    "03_intermediate":
      +materialized: view
      +schema: intermediate
    "05_marts":
      +materialized: table
      +schema: marts
